title: "Bon's ServiceNow Notes"
tagline: "ServiceNow architecture, scripts, and troubleshooting notes"
description: "ServiceNow architecture, scripts, and troubleshooting notes"

lang: en-US
timezone: Australia/Perth

url: "https://bonnow.github.io"   # 여기는 본인 주소로 변경
baseurl: ""

# theme: minima
theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

github:
  username: bonnow   # 본인 GitHub username으로 변경
