title: "ServiceNow Notes"
description: "ServiceNow architecture, scripts, and troubleshooting notes"
theme: minima
markdown: kramdown

minima:
  skin: auto
  nav_pages:
    - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md