title: "Bon's Note"
tagline: "ServiceNow architecture, scripts, and troubleshooting notes"
description: "ServiceNow architecture, scripts, and troubleshooting notes"

lang: en-US
timezone: Australia/Perth

url: "https://bonnow.github.io"
baseurl: ""

# theme: minima
theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

github:
  username: bonnow

avatar: "https://github.com/bonnow.png"

social:
  name: Bon
  email: ""
  links:
    - https://www.linkedin.com/in/bonseung-g-9a604318a/
    - https://www.youtube.com/channel/UCcWVP8-zbvaIGy-4EMhElww

paginate: 10

collections:
  tabs:
    output: true
    sort_by: order


jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# 마크다운 코드 블록(줄 번호 등) 예쁘게 설정하기
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

google_analytics:
   id: 'G-FVYFZES018'
